package ec.edu.ups.appdis.g1.clienteSOAP;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-01-06T18:17:20.362-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ClienteServicioSOAPService", 
                  wsdlLocation = "/var/folders/lb/c2plc4xn4bqgjvjy8qflgxl00000gn/T/tempdir10159906514158373731.tmp/ClienteServicioSOAP_1.wsdl",
                  targetNamespace = "http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/") 
public class ClienteServicioSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", "ClienteServicioSOAPService");
    public final static QName ClienteServicioSOAPPort = new QName("http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", "ClienteServicioSOAPPort");
    static {
        URL url = ClienteServicioSOAPService.class.getResource("/var/folders/lb/c2plc4xn4bqgjvjy8qflgxl00000gn/T/tempdir10159906514158373731.tmp/ClienteServicioSOAP_1.wsdl");
        if (url == null) {
            url = ClienteServicioSOAPService.class.getClassLoader().getResource("/var/folders/lb/c2plc4xn4bqgjvjy8qflgxl00000gn/T/tempdir10159906514158373731.tmp/ClienteServicioSOAP_1.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(ClienteServicioSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/var/folders/lb/c2plc4xn4bqgjvjy8qflgxl00000gn/T/tempdir10159906514158373731.tmp/ClienteServicioSOAP_1.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ClienteServicioSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteServicioSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteServicioSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteServicioSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteServicioSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteServicioSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClienteServicioSOAP
     */
    @WebEndpoint(name = "ClienteServicioSOAPPort")
    public ClienteServicioSOAP getClienteServicioSOAPPort() {
        return super.getPort(ClienteServicioSOAPPort, ClienteServicioSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteServicioSOAP
     */
    @WebEndpoint(name = "ClienteServicioSOAPPort")
    public ClienteServicioSOAP getClienteServicioSOAPPort(WebServiceFeature... features) {
        return super.getPort(ClienteServicioSOAPPort, ClienteServicioSOAP.class, features);
    }

}
