package ec.edu.ups.appdis.g1.clienteSOAP;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-01-06T18:17:20.352-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", name = "ClienteServicioSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteServicioSOAP {

    @WebMethod
    @RequestWrapper(localName = "prueba", targetNamespace = "http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", className = "ec.edu.ups.appdis.g1.clienteSOAP.Prueba")
    @ResponseWrapper(localName = "pruebaResponse", targetNamespace = "http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", className = "ec.edu.ups.appdis.g1.clienteSOAP.PruebaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String prueba(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "realizarTransaccion", targetNamespace = "http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", className = "ec.edu.ups.appdis.g1.clienteSOAP.RealizarTransaccion")
    @ResponseWrapper(localName = "realizarTransaccionResponse", targetNamespace = "http://servicios.sistemaTransaccional.g1.appdis.edu.ups.ec/", className = "ec.edu.ups.appdis.g1.clienteSOAP.RealizarTransaccionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String realizarTransaccion(
        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.appdis.g1.clienteSOAP.Transaccion arg0
    );
}
